# Generated by Django 3.2.13 on 2022-06-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo: ')),
                ('cnpj', models.CharField(max_length=100, unique=True)),
                ('razao_social', models.CharField(max_length=100)),
                ('fantasia', models.CharField(max_length=100)),
                ('taxa_adesao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mensalidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contato', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('quantidade_funcionarios', models.IntegerField()),
                ('vendedor', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo: ')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('P', 'Pendente'), ('C', 'Concluido'), ('A', 'Andamento')], max_length=1)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('sistema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sistema')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='sistema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sistema'),
        ),
    ]
